# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_auto_20200413_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=32, verbose_name='品牌')),
                ('model', models.CharField(max_length=32, verbose_name='型号')),
                ('number', models.CharField(max_length=32, verbose_name='编号')),
                ('leader_time', models.DateTimeField(max_length=32, verbose_name='领用时间')),
                ('leader', models.CharField(max_length=32, verbose_name='领用人')),
                ('return_time', models.DateTimeField(max_length=32, null=True, verbose_name='归还时间')),
                ('other', models.CharField(max_length=128, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '资产表',
                'verbose_name_plural': '资产表',
            },
        ),
    ]
