# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-12 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0006_auto_20200712_2347'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('语文', '语文'), ('数学', '数学'), ('英语', '英语'), ('计算机', '计算机'), ('体育', '体育'), ('音乐', '音乐'), ('美术', '美术'), ('古语', '古语')], default='语文', max_length=10, verbose_name='课程')),
                ('score', models.IntegerField(max_length=10, verbose_name='分数')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='age',
            field=models.CharField(max_length=10, verbose_name='学生年龄'),
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='phone',
            field=models.CharField(error_messages={'unique': '手机号已存在，请更换'}, max_length=11, unique=True, verbose_name='手机号'),
        ),
        migrations.AddField(
            model_name='studentcourse',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_logs.StudentMessage'),
        ),
    ]
