# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2020-07-12 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0007_auto_20200713_0006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentcourse',
            old_name='student_id',
            new_name='student',
        ),
    ]
